version: '3.9'
networks:
  my-network:
    external:
      name: jerry-network
services:
    php:
        build:
            context: ./docker
            dockerfile: php-${PHP_VERSION:?err}.Dockerfile
        container_name: ${APP_NAME:?err}-php
        restart: 'no'
        volumes:
            - './app:/var/www/html'
            - './config/php/custom.ini:/usr/local/etc/php/conf.d/zzz_custom.ini'
            - './config/php/custom.conf:/usr/local/etc/php-fpm.d/zzz_custom.conf'
        depends_on:
            - mysql
        networks:
            - my-network
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        restart: 'on-failure'
        ports:
            - '80:80'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx/conf.d:/etc/nginx/conf.d'
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './log/nginx:/var/log/nginx'
            - './config/nginx/certs:/etc/nginx/certs'
        networks:
            - my-network
    mysql:
        build:
            context: ./docker
            dockerfile: mysql.Dockerfile
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - './mysql:/var/lib/mysql'
            - './log/mysql:/var/log/mysql'
        networks:
            - my-network
