version: '3.9'
networks:
  my-network:
    external:
      name: jerry-network
services:
    php:
        build:
            context: ./docker
            dockerfile: php-${PHP_VERSION:?err}.Dockerfile
        container_name: ${APP_NAME:?err}-php
        restart: 'no'
        volumes:
            - './php-app:/var/www/html'
            - './php/config/custom.ini:/usr/local/etc/php/conf.d/zzz_custom.ini'
            - './php/config/custom.conf:/usr/local/etc/php-fpm.d/zzz_custom.conf'
        depends_on:
            - mysql
        networks:
            - my-network
        cap_add:
            - SYS_PTRACE
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.Dockerfile
        container_name: ${APP_NAME:?err}-nginx
        restart: 'on-failure'
        ports:
            - '80:80'
        links:
            - 'php'
        volumes:
            - './php-app:/var/www/html'
            - './nginx/config/conf.d:/etc/nginx/conf.d'
            - './nginx/config/nginx.conf:/etc/nginx/nginx.conf'
            - './nginx/log:/var/log/nginx'
            - './nginx/config/certs:/etc/nginx/certs'
        networks:
            - my-network
    mysql:
        build:
            context: ./docker
            dockerfile: mysql.Dockerfile
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - './mysql/data:/var/lib/mysql'
            - './mysql/log:/var/log/mysql'
        networks:
            - my-network
